version: 2
sources:
- name: eurostat_raw
  schema: public
  description: Raw Eurostat data tables loaded into the 'public' schema.
  tables:
  - name: hlth_cd_ainfo
    description: Raw Eurostat table 'hlth_cd_ainfo' loaded from source.
    columns:
    - name: freq_key
      description: 'Raw column freq_key from hlth_cd_ainfo (type: text)'
    - name: freq_label
      description: 'Raw column freq_label from hlth_cd_ainfo (type: text)'
    - name: unit_key
      description: 'Raw column unit_key from hlth_cd_ainfo (type: text)'
    - name: unit_label
      description: 'Raw column unit_label from hlth_cd_ainfo (type: text)'
    - name: sex_key
      description: 'Raw column sex_key from hlth_cd_ainfo (type: text)'
    - name: sex_label
      description: 'Raw column sex_label from hlth_cd_ainfo (type: text)'
    - name: age_key
      description: 'Raw column age_key from hlth_cd_ainfo (type: text)'
    - name: age_label
      description: 'Raw column age_label from hlth_cd_ainfo (type: text)'
    - name: icd10_key
      description: 'Raw column icd10_key from hlth_cd_ainfo (type: text)'
    - name: icd10_label
      description: 'Raw column icd10_label from hlth_cd_ainfo (type: text)'
    - name: resid_key
      description: 'Raw column resid_key from hlth_cd_ainfo (type: text)'
    - name: resid_label
      description: 'Raw column resid_label from hlth_cd_ainfo (type: text)'
    - name: geo_key
      description: 'Raw column geo_key from hlth_cd_ainfo (type: text)'
    - name: geo_label
      description: 'Raw column geo_label from hlth_cd_ainfo (type: text)'
    - name: time_key
      description: 'Raw column time_key from hlth_cd_ainfo (type: text)'
    - name: time_label
      description: 'Raw column time_label from hlth_cd_ainfo (type: text)'
    - name: linear_index
      description: 'Raw column linear_index from hlth_cd_ainfo (type: integer)'
    - name: value
      description: 'Raw column value from hlth_cd_ainfo (type: numeric)'
    - name: status_code
      description: 'Raw column status_code from hlth_cd_ainfo (type: text)'
    - name: status_label
      description: 'Raw column status_label from hlth_cd_ainfo (type: text)'
    - name: source_dataset_id
      description: 'Raw column source_dataset_id from hlth_cd_ainfo (type: text)'
  - name: hlth_cd_ainfr
    description: Raw Eurostat table 'hlth_cd_ainfr' loaded from source.
    columns:
    - name: freq_key
      description: 'Raw column freq_key from hlth_cd_ainfr (type: text)'
    - name: freq_label
      description: 'Raw column freq_label from hlth_cd_ainfr (type: text)'
    - name: unit_key
      description: 'Raw column unit_key from hlth_cd_ainfr (type: text)'
    - name: unit_label
      description: 'Raw column unit_label from hlth_cd_ainfr (type: text)'
    - name: sex_key
      description: 'Raw column sex_key from hlth_cd_ainfr (type: text)'
    - name: sex_label
      description: 'Raw column sex_label from hlth_cd_ainfr (type: text)'
    - name: age_key
      description: 'Raw column age_key from hlth_cd_ainfr (type: text)'
    - name: age_label
      description: 'Raw column age_label from hlth_cd_ainfr (type: text)'
    - name: icd10_key
      description: 'Raw column icd10_key from hlth_cd_ainfr (type: text)'
    - name: icd10_label
      description: 'Raw column icd10_label from hlth_cd_ainfr (type: text)'
    - name: resid_key
      description: 'Raw column resid_key from hlth_cd_ainfr (type: text)'
    - name: resid_label
      description: 'Raw column resid_label from hlth_cd_ainfr (type: text)'
    - name: geo_key
      description: 'Raw column geo_key from hlth_cd_ainfr (type: text)'
    - name: geo_label
      description: 'Raw column geo_label from hlth_cd_ainfr (type: text)'
    - name: time_key
      description: 'Raw column time_key from hlth_cd_ainfr (type: text)'
    - name: time_label
      description: 'Raw column time_label from hlth_cd_ainfr (type: text)'
    - name: linear_index
      description: 'Raw column linear_index from hlth_cd_ainfr (type: integer)'
    - name: value
      description: 'Raw column value from hlth_cd_ainfr (type: numeric)'
    - name: status_code
      description: 'Raw column status_code from hlth_cd_ainfr (type: text)'
    - name: status_label
      description: 'Raw column status_label from hlth_cd_ainfr (type: text)'
    - name: source_dataset_id
      description: 'Raw column source_dataset_id from hlth_cd_ainfr (type: text)'
  - name: hlth_cd_yinfo
    description: Raw Eurostat table 'hlth_cd_yinfo' loaded from source.
    columns:
    - name: freq_key
      description: 'Raw column freq_key from hlth_cd_yinfo (type: text)'
    - name: freq_label
      description: 'Raw column freq_label from hlth_cd_yinfo (type: text)'
    - name: unit_key
      description: 'Raw column unit_key from hlth_cd_yinfo (type: text)'
    - name: unit_label
      description: 'Raw column unit_label from hlth_cd_yinfo (type: text)'
    - name: sex_key
      description: 'Raw column sex_key from hlth_cd_yinfo (type: text)'
    - name: sex_label
      description: 'Raw column sex_label from hlth_cd_yinfo (type: text)'
    - name: age_key
      description: 'Raw column age_key from hlth_cd_yinfo (type: text)'
    - name: age_label
      description: 'Raw column age_label from hlth_cd_yinfo (type: text)'
    - name: icd10_key
      description: 'Raw column icd10_key from hlth_cd_yinfo (type: text)'
    - name: icd10_label
      description: 'Raw column icd10_label from hlth_cd_yinfo (type: text)'
    - name: resid_key
      description: 'Raw column resid_key from hlth_cd_yinfo (type: text)'
    - name: resid_label
      description: 'Raw column resid_label from hlth_cd_yinfo (type: text)'
    - name: geo_key
      description: 'Raw column geo_key from hlth_cd_yinfo (type: text)'
    - name: geo_label
      description: 'Raw column geo_label from hlth_cd_yinfo (type: text)'
    - name: time_key
      description: 'Raw column time_key from hlth_cd_yinfo (type: text)'
    - name: time_label
      description: 'Raw column time_label from hlth_cd_yinfo (type: text)'
    - name: linear_index
      description: 'Raw column linear_index from hlth_cd_yinfo (type: integer)'
    - name: value
      description: 'Raw column value from hlth_cd_yinfo (type: numeric)'
    - name: status_code
      description: 'Raw column status_code from hlth_cd_yinfo (type: text)'
    - name: status_label
      description: 'Raw column status_label from hlth_cd_yinfo (type: text)'
    - name: source_dataset_id
      description: 'Raw column source_dataset_id from hlth_cd_yinfo (type: text)'
  - name: hlth_cd_yinfr
    description: Raw Eurostat table 'hlth_cd_yinfr' loaded from source.
    columns:
    - name: freq_key
      description: 'Raw column freq_key from hlth_cd_yinfr (type: text)'
    - name: freq_label
      description: 'Raw column freq_label from hlth_cd_yinfr (type: text)'
    - name: unit_key
      description: 'Raw column unit_key from hlth_cd_yinfr (type: text)'
    - name: unit_label
      description: 'Raw column unit_label from hlth_cd_yinfr (type: text)'
    - name: sex_key
      description: 'Raw column sex_key from hlth_cd_yinfr (type: text)'
    - name: sex_label
      description: 'Raw column sex_label from hlth_cd_yinfr (type: text)'
    - name: age_key
      description: 'Raw column age_key from hlth_cd_yinfr (type: text)'
    - name: age_label
      description: 'Raw column age_label from hlth_cd_yinfr (type: text)'
    - name: icd10_key
      description: 'Raw column icd10_key from hlth_cd_yinfr (type: text)'
    - name: icd10_label
      description: 'Raw column icd10_label from hlth_cd_yinfr (type: text)'
    - name: resid_key
      description: 'Raw column resid_key from hlth_cd_yinfr (type: text)'
    - name: resid_label
      description: 'Raw column resid_label from hlth_cd_yinfr (type: text)'
    - name: geo_key
      description: 'Raw column geo_key from hlth_cd_yinfr (type: text)'
    - name: geo_label
      description: 'Raw column geo_label from hlth_cd_yinfr (type: text)'
    - name: time_key
      description: 'Raw column time_key from hlth_cd_yinfr (type: text)'
    - name: time_label
      description: 'Raw column time_label from hlth_cd_yinfr (type: text)'
    - name: linear_index
      description: 'Raw column linear_index from hlth_cd_yinfr (type: integer)'
    - name: value
      description: 'Raw column value from hlth_cd_yinfr (type: numeric)'
    - name: status_code
      description: 'Raw column status_code from hlth_cd_yinfr (type: text)'
    - name: status_label
      description: 'Raw column status_label from hlth_cd_yinfr (type: text)'
    - name: source_dataset_id
      description: 'Raw column source_dataset_id from hlth_cd_yinfr (type: text)'
