models:
- columns:
  - description: Code for age dimension (common across all datasets)
    name: age_code
  - description: Label for age dimension (common across all datasets)
    name: age_name
  - description: Code for freq dimension (common across all datasets)
    name: freq_code
  - description: Label for freq dimension (common across all datasets)
    name: freq_name
  - description: Code for geo dimension (common across all datasets)
    name: geo_code
  - description: Label for geo dimension (common across all datasets)
    name: geo_name
  - description: Code for icd10 dimension (common across all datasets)
    name: icd10_code
  - description: Label for icd10 dimension (common across all datasets)
    name: icd10_name
  - description: Code for resid dimension (common across all datasets)
    name: resid_code
  - description: Label for resid dimension (common across all datasets)
    name: resid_name
  - description: Code for sex dimension (common across all datasets)
    name: sex_code
  - description: Label for sex dimension (common across all datasets)
    name: sex_name
  - description: Code for time dimension (common across all datasets)
    name: time_code
  - description: Label for time dimension (common across all datasets)
    name: time_name
  - description: Code for unit dimension (common across all datasets)
    name: unit_code
  - description: Label for unit dimension (common across all datasets)
    name: unit_name
  - description: Numeric value for the indicator
    name: value
  - description: Status code for the data point
    name: status_code
  - description: Status description for the data point
    name: status_description
  - description: Original Eurostat dataset ID
    name: source_dataset_id
  - description: Source dbt staging model
    name: source_model
  description: Unified mart for Causes of death - infant mortality combining 1 related
    datasets
  name: mart_causes_of_death_-_infant_mortality
- columns:
  - description: Code for age dimension (common across all datasets)
    name: age_code
  - description: Label for age dimension (common across all datasets)
    name: age_name
  - description: Code for freq dimension (common across all datasets)
    name: freq_code
  - description: Label for freq dimension (common across all datasets)
    name: freq_name
  - description: Code for geo dimension (common across all datasets)
    name: geo_code
  - description: Label for geo dimension (common across all datasets)
    name: geo_name
  - description: Code for n_portion dimension (common across all datasets)
    name: n_portion_code
  - description: Label for n_portion dimension (common across all datasets)
    name: n_portion_name
  - description: Code for sex dimension (common across all datasets)
    name: sex_code
  - description: Label for sex dimension (common across all datasets)
    name: sex_name
  - description: Code for time dimension (common across all datasets)
    name: time_code
  - description: Label for time dimension (common across all datasets)
    name: time_name
  - description: Code for unit dimension (common across all datasets)
    name: unit_code
  - description: Label for unit dimension (common across all datasets)
    name: unit_name
  - description: 'Code for bmi dimension (available in: HLTH_EHIS_FV3M)'
    name: bmi_code
  - description: 'Label for bmi dimension (available in: HLTH_EHIS_FV3M)'
    name: bmi_name
  - description: 'Code for deg_urb dimension (available in: HLTH_EHIS_FV3U)'
    name: deg_urb_code
  - description: 'Label for deg_urb dimension (available in: HLTH_EHIS_FV3U)'
    name: deg_urb_name
  - description: 'Code for isced11 dimension (available in: HLTH_EHIS_FV3E)'
    name: isced11_code
  - description: 'Label for isced11 dimension (available in: HLTH_EHIS_FV3E)'
    name: isced11_name
  - description: 'Code for quant_inc dimension (available in: HLTH_EHIS_FV3I)'
    name: quant_inc_code
  - description: 'Label for quant_inc dimension (available in: HLTH_EHIS_FV3I)'
    name: quant_inc_name
  - description: Numeric value for the indicator
    name: value
  - description: Status code for the data point
    name: status_code
  - description: Status description for the data point
    name: status_description
  - description: Original Eurostat dataset ID
    name: source_dataset_id
  - description: Source dbt staging model
    name: source_model
  description: Unified mart for Daily consumption of fruit and vegetables combining
    4 related datasets
  name: mart_daily_consumption_of_fruit_and_vegetables
- columns:
  - description: Code for age dimension (common across all datasets)
    name: age_code
  - description: Label for age dimension (common across all datasets)
    name: age_name
  - description: Code for freq dimension (common across all datasets)
    name: freq_code
  - description: Label for freq dimension (common across all datasets)
    name: freq_name
  - description: Code for geo dimension (common across all datasets)
    name: geo_code
  - description: Label for geo dimension (common across all datasets)
    name: geo_name
  - description: Code for sex dimension (common across all datasets)
    name: sex_code
  - description: Label for sex dimension (common across all datasets)
    name: sex_name
  - description: Code for time dimension (common across all datasets)
    name: time_code
  - description: Label for time dimension (common across all datasets)
    name: time_name
  - description: 'Code for deg_urb dimension (available in: HLTH_EHIS_SK3U)'
    name: deg_urb_code
  - description: 'Label for deg_urb dimension (available in: HLTH_EHIS_SK3U)'
    name: deg_urb_name
  - description: 'Code for isced11 dimension (available in: HLTH_EHIS_SK3E)'
    name: isced11_code
  - description: 'Label for isced11 dimension (available in: HLTH_EHIS_SK3E)'
    name: isced11_name
  - description: 'Code for isced97 dimension (available in: HLTH_EHIS_DE3)'
    name: isced97_code
  - description: 'Label for isced97 dimension (available in: HLTH_EHIS_DE3)'
    name: isced97_name
  - description: 'Code for quant_inc dimension (available in: HLTH_EHIS_SK3I)'
    name: quant_inc_code
  - description: 'Label for quant_inc dimension (available in: HLTH_EHIS_SK3I)'
    name: quant_inc_name
  - description: 'Code for quantile dimension (available in: HLTH_EHIS_DE4)'
    name: quantile_code
  - description: 'Label for quantile dimension (available in: HLTH_EHIS_DE4)'
    name: quantile_name
  - description: 'Code for smoking dimension (available in: HLTH_EHIS_SK3E, HLTH_EHIS_SK3I,
      HLTH_EHIS_SK3U)'
    name: smoking_code
  - description: 'Label for smoking dimension (available in: HLTH_EHIS_SK3E, HLTH_EHIS_SK3I,
      HLTH_EHIS_SK3U)'
    name: smoking_name
  - description: 'Code for unit dimension (available in: HLTH_EHIS_SK3E, HLTH_EHIS_SK3I,
      HLTH_EHIS_SK3U)'
    name: unit_code
  - description: 'Label for unit dimension (available in: HLTH_EHIS_SK3E, HLTH_EHIS_SK3I,
      HLTH_EHIS_SK3U)'
    name: unit_name
  - description: Numeric value for the indicator
    name: value
  - description: Status code for the data point
    name: status_code
  - description: Status description for the data point
    name: status_description
  - description: Original Eurostat dataset ID
    name: source_dataset_id
  - description: Source dbt staging model
    name: source_model
  description: Unified mart for Daily smokers of cigarettes combining 5 related datasets
  name: mart_daily_smokers_of_cigarettes
- columns:
  - description: Code for age dimension (common across all datasets)
    name: age_code
  - description: Label for age dimension (common across all datasets)
    name: age_name
  - description: Code for freq dimension (common across all datasets)
    name: freq_code
  - description: Label for freq dimension (common across all datasets)
    name: freq_name
  - description: Code for geo dimension (common across all datasets)
    name: geo_code
  - description: Label for geo dimension (common across all datasets)
    name: geo_name
  - description: Code for sex dimension (common across all datasets)
    name: sex_code
  - description: Label for sex dimension (common across all datasets)
    name: sex_name
  - description: Code for time dimension (common across all datasets)
    name: time_code
  - description: Label for time dimension (common across all datasets)
    name: time_name
  - description: Code for unit dimension (common across all datasets)
    name: unit_code
  - description: Label for unit dimension (common across all datasets)
    name: unit_name
  - description: 'Code for isced11 dimension (available in: HLTH_EHIS_SK2E)'
    name: isced11_code
  - description: 'Label for isced11 dimension (available in: HLTH_EHIS_SK2E)'
    name: isced11_name
  - description: 'Code for quant_inc dimension (available in: HLTH_EHIS_SK2I)'
    name: quant_inc_code
  - description: 'Label for quant_inc dimension (available in: HLTH_EHIS_SK2I)'
    name: quant_inc_name
  - description: Numeric value for the indicator
    name: value
  - description: Status code for the data point
    name: status_code
  - description: Status description for the data point
    name: status_description
  - description: Original Eurostat dataset ID
    name: source_dataset_id
  - description: Source dbt staging model
    name: source_model
  description: Unified mart for Former daily tobacco smokers combining 2 related datasets
  name: mart_former_daily_tobacco_smokers
- columns:
  - description: Code for age dimension (common across all datasets)
    name: age_code
  - description: Label for age dimension (common across all datasets)
    name: age_name
  - description: Code for assist dimension (common across all datasets)
    name: assist_code
  - description: Label for assist dimension (common across all datasets)
    name: assist_name
  - description: Code for freq dimension (common across all datasets)
    name: freq_code
  - description: Label for freq dimension (common across all datasets)
    name: freq_name
  - description: Code for geo dimension (common across all datasets)
    name: geo_code
  - description: Label for geo dimension (common across all datasets)
    name: geo_name
  - description: Code for sex dimension (common across all datasets)
    name: sex_code
  - description: Label for sex dimension (common across all datasets)
    name: sex_name
  - description: Code for time dimension (common across all datasets)
    name: time_code
  - description: Label for time dimension (common across all datasets)
    name: time_name
  - description: Code for unit dimension (common across all datasets)
    name: unit_code
  - description: Label for unit dimension (common across all datasets)
    name: unit_name
  - description: 'Code for deg_urb dimension (available in: HLTH_EHIS_HAHLPU)'
    name: deg_urb_code
  - description: 'Label for deg_urb dimension (available in: HLTH_EHIS_HAHLPU)'
    name: deg_urb_name
  - description: 'Code for isced11 dimension (available in: HLTH_EHIS_HAHLPE)'
    name: isced11_code
  - description: 'Label for isced11 dimension (available in: HLTH_EHIS_HAHLPE)'
    name: isced11_name
  - description: 'Code for lev_limit dimension (available in: HLTH_EHIS_HAHLPD)'
    name: lev_limit_code
  - description: 'Label for lev_limit dimension (available in: HLTH_EHIS_HAHLPD)'
    name: lev_limit_name
  - description: Numeric value for the indicator
    name: value
  - description: Status code for the data point
    name: status_code
  - description: Status description for the data point
    name: status_description
  - description: Original Eurostat dataset ID
    name: source_dataset_id
  - description: Source dbt staging model
    name: source_model
  description: Unified mart for Need for help with household activities combining
    3 related datasets
  name: mart_need_for_help_with_household_activities
version: 2
